version: '3'

services:
    main:
        build: .
        image: lexonomy
        volumes:
            - <path to siteconfig.json>:/opt/service/website/siteconfig.json
            - <path to data directory>:/opt/service/data
        ports:
            - "8000:8000"

